# IROAS BOSS V2 - YAML Lint設定
# GitHub Actions ワークフローファイル検証用

extends: default

rules:
  line-length:
    max: 120
  comments:
    min-spaces-from-content: 1
  indentation:
    spaces: 2
  truthy:
    allowed-values: ['true', 'false', 'on', 'off']
  brackets:
    max-spaces-inside: 1
  braces:
    max-spaces-inside: 1