# IROAS BOSS V2 - Cloud Build設定
# 自動ビルド・デプロイ設定

steps:
  # 1. Docker イメージビルド
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build' 
      - '-f'
      - 'deployment/gcp/Dockerfile'
      - '-t' 
      - 'gcr.io/$PROJECT_ID/iroas-boss-v2-backend:$SHORT_SHA'
      - '.'
    
  # 2. Docker イメージをContainer Registryにプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push' 
      - 'gcr.io/$PROJECT_ID/iroas-boss-v2-backend:$SHORT_SHA'
  
  # 3. 本番環境デプロイ (mainブランチのみ)
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "$BRANCH_NAME" == "main" ]]; then
          gcloud run deploy iroas-boss-v2-backend \
            --image gcr.io/$PROJECT_ID/iroas-boss-v2-backend:$SHORT_SHA \
            --region asia-northeast1 \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars="DATABASE_URL=$$DATABASE_URL_PRODUCTION,REDIS_URL=$$REDIS_URL_PRODUCTION,SECRET_KEY=$$SECRET_KEY_PRODUCTION" \
            --memory 2Gi \
            --cpu 2 \
            --max-instances 10 \
            --min-instances 1 \
            --concurrency 100 \
            --timeout 900
        fi
    secretEnv: ['DATABASE_URL_PRODUCTION', 'REDIS_URL_PRODUCTION', 'SECRET_KEY_PRODUCTION']
  
  # 4. ステージング環境デプロイ (developブランチ)
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "$BRANCH_NAME" == "develop" ]]; then
          gcloud run deploy iroas-boss-v2-backend-staging \
            --image gcr.io/$PROJECT_ID/iroas-boss-v2-backend:$SHORT_SHA \
            --region asia-northeast1 \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars="DATABASE_URL=$$DATABASE_URL_STAGING,REDIS_URL=$$REDIS_URL_STAGING,SECRET_KEY=$$SECRET_KEY_STAGING" \
            --memory 1Gi \
            --cpu 1 \
            --max-instances 5 \
            --min-instances 0 \
            --concurrency 50 \
            --timeout 600
        fi
    secretEnv: ['DATABASE_URL_STAGING', 'REDIS_URL_STAGING', 'SECRET_KEY_STAGING']

# 環境変数の暗号化された値を使用
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/database-url-production/versions/latest
    env: 'DATABASE_URL_PRODUCTION'
  - versionName: projects/$PROJECT_ID/secrets/database-url-staging/versions/latest  
    env: 'DATABASE_URL_STAGING'
  - versionName: projects/$PROJECT_ID/secrets/redis-url-production/versions/latest
    env: 'REDIS_URL_PRODUCTION'
  - versionName: projects/$PROJECT_ID/secrets/redis-url-staging/versions/latest
    env: 'REDIS_URL_STAGING'
  - versionName: projects/$PROJECT_ID/secrets/secret-key-production/versions/latest
    env: 'SECRET_KEY_PRODUCTION'
  - versionName: projects/$PROJECT_ID/secrets/secret-key-staging/versions/latest
    env: 'SECRET_KEY_STAGING'

# ビルドオプション
options:
  machineType: 'E2_HIGHCPU_8'
  substitution_option: 'ALLOW_LOOSE'
  logging: CLOUD_LOGGING_ONLY

# タイムアウト設定
timeout: 1200s

# 置換変数
substitutions:
  # デフォルト値設定
  _REGION: 'asia-northeast1'
  _SERVICE_NAME: 'iroas-boss-v2-backend'